import { Router } from 'express';
import { getUserChats, createChat, sendMessage, getChatMessages } from '../controllers/chat.controller.js';
import { validate } from '../middleware/validate.middleware.js';
import { authenticateJWT } from '../middleware/auth.middleware.js';
import { chatSchema, messageSchema } from '../schemas/chat.schema.js';
const router = Router();
router.get('/users/:id/chats', authenticateJWT, getUserChats);
router.post('/chats', authenticateJWT, validate(chatSchema), createChat);
router.post('/chats/:chatId/messages', authenticateJWT, validate(messageSchema), sendMessage);
router.get('/chats/:chatId/messages', authenticateJWT, getChatMessages);
export default router;
